NDefines.NAI.PEACE_TERMS_TAKE_MANDATE_BASE_MULT = 3000.0 
NDefines.NAI.WANT_TRIBUTARY_LOST_MANDATE = 50
NDefines.NAI.PEACE_TERMS_TRIBUTARY_BASE_MULT = -1000.0
NDefines.NDiplomacy.CELESTIAL_EMPIRE_DEFAULT_INFLUENCE = 70		-- Starting value for Mandate value of a new Chinese Emperor
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MODIFIER_THRESHOLD = 35		-- Value of Mandate above which the positive Mandate Modifier is used instead of the negative one
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STABILITY = 0	-- Yearly change of Mandate for each point of positive stability
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STATE_WITH_PROSPERITY = 0.1	-- Yearly change of Mandate for each State with prosperity.
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_DEVASTATION = 0	-- Yearly change of Mandate for each hundred devastated development (scaled to devastation).
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_TRIBUTARY_DEV = 0-- Yearly change of Mandate for each hundred development tributary state.
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_NONTRIBUTARY_DEV = 0	-- Yearly change of Mandate for each hundred development of neighbouring states that are not the Emperor's tributaries
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_FROM_DEFENDING = 15	-- How much Mandate is gained when successfully defending the Emperor title.
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_5_LOANS = 0
NDefines.NDiplomacy.DIPLOMATIC_ACTION_TRIBUTARY_EMPIRE_FACTOR = 35
NDefines.NReligion.CHANGE_SECONDARY_PRESTIGE_HIT = -10
NDefines.NReligion.MIN_HARMONIZE_DEVELOPMENT = 1
NDefines.NReligion.STARTING_HARMONY = 100.0					-- Confucian countries start with this.
NDefines.NReligion.YEARLY_HARMONY_INCREASE = 0.0
NDefines.NReligion.HARMONY_LOSS_PER_DEV_CONVERTED = 0
NDefines.NReligion.YEARLY_HARMONY_INCREASE_WHEN_HARMONIZING = -6
NDefines.NReligion.YEARLY_HARMONIZATION_PROGRESS = 0.0125
NDefines.NMilitary.BANNER_DISCIPLINE_BONUS = 0.05
NDefines.NMilitary.BANNER_MANPOWER_USAGE = 0.25
NDefines.NMilitary.BANNER_REINFORCE_SPEED = -0.5
NDefines.NMilitary.BANNER_MAINTENANCE_COST = 1.5
NDefines.NMilitary.BANNER_AGE_MULTIPLIER = 0.0
NDefines.NMilitary.BANNER_STARTING_STRENGTH = 1.0	
NDefines.NCountry.CORRUPTION_FROM_BANNERS = 0
NDefines.NCountry.DIVERT_TRADE_FRACTION = 1
NDefines.NCountry.DEVELOPMENT_ON_CONTINENT_FOR_NEW_CAPITAL = 0
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_COST = 50			-- Mandate cost of enacting a new reform for the Emperor of China.
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_STABILITY_COST = 0 -- Stability cost of enacting a new reform for the Emperor of China
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_MIN_VALUE = 90
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_5_LOANS = 0

NDefines.NDiplomacy.TRIBUTE_BASE_CASH = 0.125					-- Tributary State: Part of yearly income given in tribute
NDefines.NDiplomacy.TRIBUTE_BASE_ADM = 0.04				-- Tributary State: Part Adm tribute, mulitplied by total development
NDefines.NDiplomacy.TRIBUTE_BASE_DIP = 0.04						-- Tributary State: Part Dip tribute, mulitplied by total development
NDefines.NDiplomacy.TRIBUTE_BASE_MIL = 0.04
NDefines.NDiplomacy.TRIBUTE_MAX_MONARCH_POWER = 20.0			-- Tributary State: Max Adm/Dip/Mil per Tributary
NDefines.NDiplomacy.TRIBUTE_BASE_MANPOWER = 0.25					-- Tributary State: Part of yearly manpower given in tribute
NDefines.NCountry.MAXIMUM_ADVISOR_SKILL = 5
NDefines.NCountry.PS_CHANGE_CULTURE = 10
NDefines.NCountry.CULTURE_COST_DIFF_ORIGINAL = -50			-- Difference in cost in percent to convert to original culture.
NDefines.NCountry.CULTURE_COST_DIFF_ADJACENT = -25			-- Difference in cost in percent to convert to adjacent culture.
NDefines.NCountry.CULTURE_COST_DIFF_PRIMARY = 0				-- Difference in cost in percent to convert to primary culture.
NDefines.NCountry.MONTHS_TO_CHANGE_CULTURE = 10
NDefines.NDiplomacy.PEACE_COST_TAKE_MANDATE = 100
